from django.urls import path

from . import api, views

urlpatterns = [
    path("api/v1/client/manifest", api.manifest, name="client-manifest"),
    path("api/v1/client/tasks", api.tasks, name="client-tasks"),
    path("api/v1/client/results", api.results, name="client-results"),
    path("", views.dashboard, name="dashboard"),
    path("partials/dashboard/", views.dashboard_partial, name="dashboard-partial"),
    path("subscriptions/", views.subscription_list, name="subscriptions"),
    path("subscriptions/new/", views.subscription_form, name="subscription-new"),
    path("subscriptions/<int:pk>/edit/", views.subscription_form, name="subscription-edit"),
    path("subscriptions/<int:pk>/delete/", views.subscription_delete, name="subscription-delete"),
    path("subscriptions/<int:pk>/sync/", views.subscription_sync, name="subscription-sync"),
    path("nodes/<int:pk>/edit/", views.node_form, name="node-edit"),
    path("nodes/<int:pk>/check/", views.check_now, name="check-now"),
    path("tcp/", views.monitor_page, {"kind": "tcp"}, name="tcp-monitors"),
    path("partials/tcp/", views.monitor_partial, {"kind": "tcp"}, name="tcp-partial"),
    path("tcp/new/", views.monitor_form, {"kind": "tcp"}, name="tcp-new"),
    path("tcp/<int:pk>/edit/", views.monitor_form, {"kind": "tcp"}, name="tcp-edit"),
    path("tcp/<int:pk>/delete/", views.monitor_delete, {"kind": "tcp"}, name="tcp-delete"),
    path("tcp/<int:pk>/check/", views.monitor_check_now, {"kind": "tcp"}, name="tcp-check"),
    path("https/", views.monitor_page, {"kind": "https"}, name="https-monitors"),
    path("partials/https/", views.monitor_partial, {"kind": "https"}, name="https-partial"),
    path("https/new/", views.monitor_form, {"kind": "https"}, name="https-new"),
    path("https/<int:pk>/edit/", views.monitor_form, {"kind": "https"}, name="https-edit"),
    path("https/<int:pk>/delete/", views.monitor_delete, {"kind": "https"}, name="https-delete"),
    path("https/<int:pk>/check/", views.monitor_check_now, {"kind": "https"}, name="https-check"),
    path("test-points/", views.test_point_list, name="test-points"),
    path("test-points/new/", views.test_point_form, name="test-point-new"),
    path("test-points/<int:pk>/edit/", views.test_point_form, name="test-point-edit"),
    path("test-points/<int:pk>/delete/", views.test_point_delete, name="test-point-delete"),
    path("settings/", views.settings_view, name="settings"),
]
