# Generated by Django 5.2.16 on 2026-07-11 07:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor_type', models.CharField(db_index=True, max_length=20)),
                ('monitor_id', models.PositiveIntegerField(db_index=True)),
                ('success', models.BooleanField()),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='HTTPMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='名称')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('interval_seconds', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(10)], verbose_name='检查间隔（秒）')),
                ('timeout_seconds', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='超时（秒）')),
                ('status', models.CharField(choices=[('unknown', '未知'), ('up', '正常'), ('down', '异常'), ('disabled', '停用')], default='unknown', editable=False, max_length=10)),
                ('last_checked_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('next_check_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('last_changed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_latency_ms', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('last_error', models.TextField(blank=True, editable=False)),
                ('consecutive_successes', models.PositiveIntegerField(default=0, editable=False)),
                ('consecutive_failures', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=1000, verbose_name='URL')),
                ('expected_status_min', models.PositiveIntegerField(default=200, verbose_name='最小状态码')),
                ('expected_status_max', models.PositiveIntegerField(default=399, verbose_name='最大状态码')),
                ('keyword', models.CharField(blank=True, max_length=200, verbose_name='响应关键词')),
                ('verify_tls', models.BooleanField(default=True, verbose_name='验证 TLS 证书')),
                ('follow_redirects', models.BooleanField(default=True, verbose_name='跟随重定向')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('success', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bark_url', models.URLField(blank=True, help_text='例如 https://api.day.app/设备Key', max_length=1000, verbose_name='Bark 地址')),
                ('enabled', models.BooleanField(default=False, verbose_name='启用通知')),
                ('failure_threshold', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)], verbose_name='连续失败阈值')),
                ('recovery_threshold', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)], verbose_name='连续成功阈值')),
                ('group', models.CharField(blank=True, default='SrvCheck', max_length=80, verbose_name='通知分组')),
            ],
        ),
        migrations.CreateModel(
            name='TCPMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='名称')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('interval_seconds', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(10)], verbose_name='检查间隔（秒）')),
                ('timeout_seconds', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='超时（秒）')),
                ('status', models.CharField(choices=[('unknown', '未知'), ('up', '正常'), ('down', '异常'), ('disabled', '停用')], default='unknown', editable=False, max_length=10)),
                ('last_checked_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('next_check_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('last_changed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_latency_ms', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('last_error', models.TextField(blank=True, editable=False)),
                ('consecutive_successes', models.PositiveIntegerField(default=0, editable=False)),
                ('consecutive_failures', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.CharField(max_length=255, verbose_name='主机')),
                ('port', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='端口')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='XraySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='名称')),
                ('url', models.URLField(max_length=2000, verbose_name='订阅 URL')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('update_interval_minutes', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(5)], verbose_name='同步间隔（分钟）')),
                ('check_interval_seconds', models.PositiveIntegerField(default=300, validators=[django.core.validators.MinValueValidator(30)], verbose_name='节点检查间隔（秒）')),
                ('timeout_seconds', models.PositiveIntegerField(default=15, verbose_name='超时（秒）')),
                ('last_synced_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('next_sync_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('last_error', models.TextField(blank=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='XrayNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='名称')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('interval_seconds', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(10)], verbose_name='检查间隔（秒）')),
                ('timeout_seconds', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='超时（秒）')),
                ('status', models.CharField(choices=[('unknown', '未知'), ('up', '正常'), ('down', '异常'), ('disabled', '停用')], default='unknown', editable=False, max_length=10)),
                ('last_checked_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('next_check_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('last_changed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_latency_ms', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('last_error', models.TextField(blank=True, editable=False)),
                ('consecutive_successes', models.PositiveIntegerField(default=0, editable=False)),
                ('consecutive_failures', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('protocol', models.CharField(max_length=20)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('share_link', models.TextField()),
                ('active_in_subscription', models.BooleanField(default=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='monitors.xraysubscription')),
            ],
            options={
                'ordering': ['subscription', 'name'],
                'constraints': [models.UniqueConstraint(fields=('subscription', 'fingerprint'), name='unique_subscription_node')],
            },
        ),
    ]
