# Generated by Django 5.2.16 on 2026-07-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkresult',
            name='proxy_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
