# Generated by Django 5.2.16 on 2026-07-11 08:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0002_checkresult_proxy_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xraysubscription',
            name='update_interval_minutes',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(5)], verbose_name='订阅更新间隔（分钟）'),
        ),
    ]
