# Generated by Django 5.2.16 on 2026-07-11 08:38

import django.db.models.deletion
from django.db import migrations, models
from datetime import timedelta
from django.utils import timezone


def backfill_snapshots(apps, schema_editor):
    CheckResult = apps.get_model('monitors', 'CheckResult')
    Snapshot = apps.get_model('monitors', 'XrayNodeSnapshot')
    now = timezone.now()
    results = CheckResult.objects.filter(
        monitor_type='xray', checked_at__gte=now - timedelta(days=8)
    ).order_by('checked_at')
    hourly, daily = {}, {}
    for result in results.iterator():
        if result.checked_at >= now - timedelta(hours=15):
            bucket = result.checked_at.replace(minute=0, second=0, microsecond=0)
            hourly[(result.monitor_id, bucket)] = result
        if result.success and result.proxy_ip:
            local = timezone.localtime(result.checked_at)
            bucket = local.replace(hour=0, minute=0, second=0, microsecond=0)
            daily[(result.monitor_id, bucket)] = result
    rows = []
    for (node_id, bucket), result in hourly.items():
        rows.append(Snapshot(node_id=node_id, kind='hourly', bucket_start=bucket, success=result.success, proxy_ip=result.proxy_ip, latency_ms=result.latency_ms, checked_at=result.checked_at))
    for (node_id, bucket), result in daily.items():
        rows.append(Snapshot(node_id=node_id, kind='daily', bucket_start=bucket, success=True, proxy_ip=result.proxy_ip, latency_ms=result.latency_ms, checked_at=result.checked_at))
    Snapshot.objects.bulk_create(rows, ignore_conflicts=True)
    CheckResult.objects.filter(monitor_type='xray').update(proxy_ip=None)


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0003_alter_xraysubscription_update_interval_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='XrayNodeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('hourly', '小时'), ('daily', '每日')], max_length=10)),
                ('bucket_start', models.DateTimeField(db_index=True)),
                ('success', models.BooleanField()),
                ('proxy_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('checked_at', models.DateTimeField()),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='monitors.xraynode')),
            ],
            options={
                'ordering': ['-bucket_start'],
                'indexes': [models.Index(fields=['kind', 'bucket_start'], name='xray_snap_kind_bucket_idx')],
                'constraints': [models.UniqueConstraint(fields=('node', 'kind', 'bucket_start'), name='unique_xray_snapshot_bucket')],
            },
        ),
        migrations.RunPython(backfill_snapshots, migrations.RunPython.noop),
    ]
