# Generated by Django 5.2.16 on 2026-07-20 07:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0009_client_server_architecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTTPSMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='名称')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('check_interval_seconds', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(30)], verbose_name='检查间隔（秒）')),
                ('status', models.CharField(choices=[('unknown', '未知'), ('up', '正常'), ('down', '异常'), ('disabled', '停用')], default='unknown', editable=False, max_length=10)),
                ('incident_open', models.BooleanField(default=False, editable=False)),
                ('last_checked_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_changed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=1000, verbose_name='URL')),
                ('expected_status_min', models.PositiveIntegerField(default=200, verbose_name='最小状态码')),
                ('expected_status_max', models.PositiveIntegerField(default=399, verbose_name='最大状态码')),
                ('keyword', models.CharField(blank=True, max_length=200, verbose_name='响应关键词')),
                ('verify_tls', models.BooleanField(default=True, verbose_name='验证 TLS 证书')),
                ('follow_redirects', models.BooleanField(default=True, verbose_name='跟随重定向')),
                ('timeout_seconds', models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='超时（秒）')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TCPMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='名称')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('check_interval_seconds', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(30)], verbose_name='检查间隔（秒）')),
                ('timeout_seconds', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='超时（秒）')),
                ('status', models.CharField(choices=[('unknown', '未知'), ('up', '正常'), ('down', '异常'), ('disabled', '停用')], default='unknown', editable=False, max_length=10)),
                ('incident_open', models.BooleanField(default=False, editable=False)),
                ('last_checked_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_changed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.CharField(max_length=255, verbose_name='主机')),
                ('port', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='端口')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='clientresult',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_results', to='monitors.xraynode'),
        ),
        migrations.AlterField(
            model_name='manualchecktask',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manual_tasks', to='monitors.xraynode'),
        ),
        migrations.AddField(
            model_name='clientresult',
            name='https_monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_results', to='monitors.httpsmonitor'),
        ),
        migrations.AddField(
            model_name='manualchecktask',
            name='https_monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manual_tasks', to='monitors.httpsmonitor'),
        ),
        migrations.CreateModel(
            name='MonitorSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('hourly', '小时'), ('daily', '每日')], max_length=10)),
                ('bucket_start', models.DateTimeField(db_index=True)),
                ('success', models.BooleanField()),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('checked_at', models.DateTimeField()),
                ('https_monitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='monitors.httpsmonitor')),
                ('test_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_snapshots', to='monitors.testpoint')),
                ('tcp_monitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='monitors.tcpmonitor')),
            ],
            options={
                'ordering': ['-bucket_start'],
            },
        ),
        migrations.AddField(
            model_name='clientresult',
            name='tcp_monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_results', to='monitors.tcpmonitor'),
        ),
        migrations.AddField(
            model_name='manualchecktask',
            name='tcp_monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manual_tasks', to='monitors.tcpmonitor'),
        ),
        migrations.AddIndex(
            model_name='clientresult',
            index=models.Index(fields=['tcp_monitor', 'test_point', '-received_at'], name='client_result_tcp_idx'),
        ),
        migrations.AddIndex(
            model_name='clientresult',
            index=models.Index(fields=['https_monitor', 'test_point', '-received_at'], name='client_result_https_idx'),
        ),
        migrations.AddConstraint(
            model_name='clientresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('https_monitor__isnull', True), ('node__isnull', False), ('tcp_monitor__isnull', True)), models.Q(('https_monitor__isnull', True), ('node__isnull', True), ('tcp_monitor__isnull', False)), models.Q(('https_monitor__isnull', False), ('node__isnull', True), ('tcp_monitor__isnull', True)), _connector='OR'), name='client_result_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='manualchecktask',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('https_monitor__isnull', True), ('node__isnull', False), ('tcp_monitor__isnull', True)), models.Q(('https_monitor__isnull', True), ('node__isnull', True), ('tcp_monitor__isnull', False)), models.Q(('https_monitor__isnull', False), ('node__isnull', True), ('tcp_monitor__isnull', True)), _connector='OR'), name='manual_task_exactly_one_target'),
        ),
        migrations.AddIndex(
            model_name='monitorsnapshot',
            index=models.Index(fields=['kind', 'bucket_start'], name='monitor_snap_bucket_idx'),
        ),
        migrations.AddConstraint(
            model_name='monitorsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('https_monitor__isnull', True), ('tcp_monitor__isnull', False)), models.Q(('https_monitor__isnull', False), ('tcp_monitor__isnull', True)), _connector='OR'), name='monitor_snapshot_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='monitorsnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(('tcp_monitor__isnull', False)), fields=('tcp_monitor', 'test_point', 'kind', 'bucket_start'), name='unique_tcp_snapshot_bucket'),
        ),
        migrations.AddConstraint(
            model_name='monitorsnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(('https_monitor__isnull', False)), fields=('https_monitor', 'test_point', 'kind', 'bucket_start'), name='unique_https_snapshot_bucket'),
        ),
    ]
